### ISSUE TITLE
move socket communication to python script

### ISSUE THREAD

**Issue by vanhauser-thc** [airbus-cyber/afl_ghidra_emu#1]
Hi guys,

I see that you implemented a socket feature in afl++.
I don't think this is needed, as lots of other solutation (qemu_mode, unicorn_mode, frida_mode, etc.) also rely on doing their own thing and passed coverage information and execution results to afl-fuzz.
Wouldnt it be possible to write coverage information to the shared mem and report execution results to the file descriptor in afl_bridge_external.py instead?

cool work!

**Comment by c-eax** [comment]
Hi vhthc,
Good point, 
I will try to write code coverage data directly to AFL shared map mem . So no more need to open tcp socket in afl-fuzz.

Thanks!

**Comment by vanhauser-thc** [comment]
this will also improve the speed, but I think ghidra is the major slow down anyway ;)

**Comment by c-eax** [comment]
afl_bridge_external.py was replaced by afl_bridge_external.c 
From now, It reports coverage information and exit status to AFL++ using shared memory and file descriptor:
- AFLplusplus-socket-mode (AFLplusplus fork) is no more needed
- afl_ghidra_emu is fully compatible with AFL++ without modifications
- Performance was largely improved (around x30 faster)

Thanks @vanhauser-thc for your help on AFL++ internals!

**Comment by vanhauser-thc** [comment]
great job!
